name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # chạy 2 lần mỗi ngày
  workflow_dispatch:         # cho phép chạy tay
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: fbtuan2
          outputs: dist/snake.svg

      - name: Deploy Snake to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist